
### Results {.tabset}
 

#### ICL 

```{r , echo=FALSE}
plot.coseq.res <- FlomicsMultiAssay@ExperimentList[[paste0(data,".filtred")]]@metadata[["CoExpAnal"]]$plots
par(mar = c(4, 4, .5, .1))
plot.coseq.res$ICL 
```

#### logLike 

```{r ,echo=FALSE}
#plot.coseq.res <- FlomicsMultiAssay@ExperimentList[[paste0(data,".filtred")]]@metadata[["CoExpAnal"]]$plots
par(mar = c(4, 4, .5, .1))
plot.coseq.res$logLike
```

#### profiles  

```{r , echo=FALSE}
par(mar = c(4, 4, .5, .1))
plot.coseq.res$profiles 
```

#### boxplots

```{r , echo=FALSE}
par(mar = c(4, 4, .5, .1))
plot.coseq.res$boxplots
```

#### probapost_boxplots 

```{r , echo=FALSE}
#plot.coseq.res <- FlomicsMultiAssay@ExperimentList[[paste0(data,".filtred")]]@metadata[["CoExpAnal"]]$plots
par(mar = c(4, 4, .5, .1))
plot.coseq.res$probapost_boxplots 
```

#### probapost_barplots

```{r , echo=FALSE}
par(mar = c(4, 4, .5, .1))
plot.coseq.res$probapost_barplots
```

#### probapost_barplots

```{r , echo=FALSE}
par(mar = c(4, 4, .5, .1))
plot.coseq.res$probapost_histogram
```   


