# Packages

library(plotly)
library(DT)
library(magrittr)
library(coseq)
library(edgeR)
library(tibble)
library(dplyr)
library(tidyr)
library(stringr)
library(data.table)
library(shinyWidgets)
library(SummarizedExperiment)
library(gridExtra)
library(MultiAssayExperiment)
library(FactoMineR)
library(ggplot2)
library(reshape2)
library(kableExtra)
library(shinyBS)
source("LoadOmicsDataModules.R")
source("ExperimentalDesignModule.R")
source("DataExploratoryModules.R")
source("DiffExpressionModules.R")
source("CoExpressionModules.R")
source("AnnotationEnrichment.R")
source("commonModules.R")
source("coverPage.R")

SupportedOmics <- c("RNAseq", "proteomics", "metabolomics")

#enableBookmarking(store = "server")

