
<!-- <details> -->

```{r , echo=FALSE , message=FALSE, warning=FALSE}

# create export data
listnameDir <- paste0(annotDir,"/", contrastName2contrastDir(listname),"/",domain,"/")
dir.create(path=listnameDir)

knitr::opts_chunk$set(
  fig.path=listnameDir
)
```


### `r listname` {.tabset}

#### `r domain` {.tabset}

##### overrepresented plot

```{r top50_over_represented_terms, echo=FALSE, out.width = "50%", message=FALSE, warning=FALSE,}

p <- Enrichment.plot(object = dataset.SE, listNames = listname, from = annot,
                                                  Over_Under = "overrepresented",
                                                  top = 50 , domain = domain)
print(p)

```

##### underrepresented plot

```{r top50_under_represented_terms, echo=FALSE, out.width = "70%", message=FALSE, warning=FALSE}

  p <- Enrichment.plot(object = dataset.SE, listNames = listname, from = annot,
                                                    Over_Under = "underrepresented",
                                                    top = 50 , domain = domain)
  print(p)

```

##### table

```{r , results='asis', echo = FALSE, out.width = "70%"}

  reactable(dplyr::filter(dataset.SE@metadata[[annot]][["results"]][[listname]][["Over_Under_Results"]],Domain==domain),
            defaultPageSize = 6, searchable = TRUE, paginationType = "simple",
            columns = list(
              Decision = colDef(
                  style = function(value) {
                      color <- if (value == "overrepresented") {
                        "#008000"
                      } else if (value == "underrepresented") {
                        "#e00000"
                      }
                      list(fontWeight = 600, color = color)
                  }
                )
              )
            )

  write.table(dplyr::filter(dataset.SE@metadata[[annot]][["results"]][[listname]][["Over_Under_Results"]],Domain==domain),
             file=paste0(listnameDir,"Table_of_Over_Under_Represented_terms.txt"),
             sep="\t",quote=FALSE,col.names=TRUE,row.names=FALSE)
```

<!-- </details> -->



