
```{r , echo=FALSE , message=FALSE, warning=FALSE}
annotDir <- paste0(dataDir,"/","04-Enrichment_analysis_CPR/")
dir.create(path=annotDir)

knitr::opts_chunk$set(
  fig.path=annotDir
)
```

<br>

* Enrichment analysis for `r ontology` ontology:

Enrichment analysis was carried out for each selected contrast thanks to  the clusterprofiler R-package. 
Lists of DE features have been analyzed for enrichment using `r ontology` ontology.

Summary:

<!-- ### summary per ontology and per contrast -->

```{r ,  message=FALSE, warning=FALSE, echo=FALSE, results="asis", out.width = "50%"}
kable_styling(kable(dataset.SE@metadata[[annot]][[ontology]]$summary, row.names=FALSE, caption=NULL, format="html"), font_size=12)
```

Results by contrasts:

*Please click on the arrows to scroll down the results and click on the figure for zooming*

```{r , message=FALSE, warning=FALSE, echo=FALSE}
out <- NULL
for (listname  in names(dataset.SE@metadata[[annot]][[ontology]]$enrichResult)){
      out <- c(out, knitr::knit_child(paste0(path.package("RFLOMICS"), "/RFLOMICSapp/","report_06_annot_enrich_per_list_per_Domain_CPR.Rmd"), quiet=TRUE))
}

knitr::asis_output(out)
```




