
<!-- <details> -->
<!--   <summary>`r listname`</summary> -->

```{r , echo=FALSE , message=FALSE, warning=FALSE}
# create export data
listnameDir <- paste0(annotDir,"/",contrastName2contrastDir(listname),"/")
dir.create(path=listnameDir)

knitr::opts_chunk$set(
  fig.path=listnameDir
)
```


### `r listname` {.tabset}

#### overrepresented plot

```{r over_represented_Domain_top50, echo=FALSE, out.width = "50%", message=FALSE, warning=FALSE,}

for(domain in unique(dataset.SE@metadata[[annot]]$results[[listname]]$Over_Under_Results$Domain)){
p <- Enrichment.plot(object = dataset.SE, listNames = listname, from = annot,
                                                  Over_Under = "overrepresented",
                                                  top = 50 , domain = domain)
print(p)
}

```

#### underrepresented plot

```{r under_represented_Domain_top50, echo=FALSE, out.width = "70%", message=FALSE, warning=FALSE}

for(domain in unique(dataset.SE@metadata[[annot]]$results[[listname]]$Over_Under_Results$Domain)){
  p <- Enrichment.plot(object = dataset.SE, listNames = listname, from = annot,
                                                    Over_Under = "underrepresented",
                                                    top = 50 , domain = domain)
  print(p)
}

```

#### table

```{r , results='asis', echo = FALSE, out.width = "70%"}

  reactable(dataset.SE@metadata[[annot]][["results"]][[listname]][["Over_Under_Results"]],
            defaultPageSize = 6, searchable = TRUE, paginationType = "simple",
            columns = list(
              Decision = colDef(
                  style = function(value) {
                      color <- if (value == "overrepresented") {
                        "#008000"
                      } else if (value == "underrepresented") {
                        "#e00000"
                      }
                      list(fontWeight = 600, color = color)
                  }
                )
              )
            )

  write.table(dataset.SE@metadata[[annot]][["results"]][[listname]][["Over_Under_Results"]],
             file=paste0(listnameDir,"Table_of_Over_Under_Represented_Domain.txt"),
             sep="\t",quote=FALSE,col.names=TRUE,row.names=FALSE)
```

<!-- </details> -->


