
```{r}
listnameDirDom <- paste0(annotDir, "/", RFLOMICS:::contrastName2contrastDir(listname),"/", ontology, "/", domain, "/")
dir.create(path=listnameDirDom, recursive = TRUE)

knitr::opts_chunk$set(
    fig.path = listnameDirDom
)
```

`r if(typePlot!="dotplot") {"\\begin{comment}"}`

```{r dotplot, fig.width = 15, fig.height = 7, eval = (typePlot == "dotplot")}
dataPlot <-  enrichRes[[domain]]
if (nrow(dataPlot) > 0) {
    p <- enrichplot::dotplot(dataPlot, showCategory = 15) + 
        ggplot2::ggtitle(paste0(listname, "\nEnrichment analysis result on domain ", 
                                domain, "\nFirst 15 enriched terms"))
    print(p)
}else{print(paste0(listname, " - in domain: ", 
                   domain, 
                   " - There was no enriched term found in this setting."))
}
```

`r if(typePlot!="dotplot") {"\\end{comment}"}`

`r if(typePlot!="heatplot") {"\\begin{comment}"}`

```{r heatplot, fig.width = 15, fig.height = 7, eval = (typePlot == "heatplot")}
dataPlot <-  enrichRes[[domain]]
if (nrow(dataPlot) > 0) {
    p <-  enrichplot::heatplot(dataPlot, showCategory = 15, foldChange = log2FC_vect) + 
        ggplot2::labs(fill="log2FC") + 
        ggplot2::scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
        ggplot2::theme(axis.text.y = ggplot2::element_text(size = 10)) + 
        ggplot2::ggtitle(paste0(listname, 
                                " - Enrichment analysis result on domain ", 
                                domain, 
                                "\nFirst 15 enriched terms"))
    suppressMessages(print(p))# delete warnings for scale fill replacement
}else{print(paste0(listname, " - in domain: ", 
                   domain, 
                   " - There was no enriched term found in this setting."))}
```

`r if(typePlot!="heatplot") {"\\end{comment}"}`

`r if(typePlot!="cnetplot") {"\\begin{comment}"}`

```{r CnetPlot, fig.width = 15, fig.height = 7, eval = (typePlot == "cnetplot")}
dataPlot <-  enrichRes[[domain]]
if(nrow(dataPlot)>0){
    p <- enrichplot::cnetplot(dataPlot, showCategory = 15, foldChange = log2FC_vect, node_label = "category") + 
        ggplot2::guides(colour=ggplot2::guide_colourbar(title = "log2FC")) +
        ggplot2::scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) + 
        ggplot2::ggtitle(paste0(listname, " - Enrichment analysis result on domain ", domain, "\nFirst 15 enriched terms"))
    suppressMessages(print(p)) # delete warnings for scale fill replacement
}else{print(paste0(listname, " - in domain: ", domain, " - There was no enriched term found in this setting."))}
```

`r if(typePlot!="cnetplot") {"\\end{comment}"}`

`r if(typePlot!="table") {"\\begin{comment}"}`

```{r tableCPR, fig.width = 15, fig.height = 7, eval = (typePlot == "table")}
dataPlot <-  enrichRes[[domain]]
write.table(dataPlot@result[dataPlot@result$p.adjust < dataPlot@pvalueCutoff, ],
            file=paste0(listnameDir,"Table_of_Enriched_terms_for_", 
                        domain,"_","pval_",
                        dataPlot@pvalueCutoff,".txt"),
            sep="\t",
            quote=FALSE,
            col.names=TRUE,
            row.names=FALSE)
```

`r if(typePlot!="table") {"\\end{comment}"}`