---
title: "RFLOMICS report"
author: "nadia.bessoltane@inra.fr "
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    df_print: paged
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    theme: united
params: 
  pngDir: NA
  FEdata: NA
---


```{r , include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r parameters, include=FALSE}

load(params$FEdata)
pngDir <- params$pngDir

```



# Experimental Design :

> sample sheet

```{r Design, echo=FALSE, message=TRUE, warning=TRUE}
FlomicsMultiAssay@colData
```


> Factor type

```{r factor, echo=FALSE, message=TRUE, warning=TRUE}
FlomicsMultiAssay@metadata$design@Factors.Type
```

> Check Experimental Design Completeness

```{r CheckDesign, echo=FALSE, message=TRUE, warning=TRUE}
CheckExpDesignCompleteness(FlomicsMultiAssay@metadata$design)
```

> Statistical model

```{r model, echo=FALSE, message=TRUE, warning=TRUE}
FlomicsMultiAssay@metadata$design@Model.formula

```

> Selected hypothesis

```{r contrast, echo=FALSE, message=TRUE, warning=TRUE}

FlomicsMultiAssay@metadata$design@Contrasts.Sel$contrastName 

```


`r if(length(FlomicsMultiAssay@metadata$omicList) == 0) {"\\begin{comment}"}`


```{r analysis, message=FALSE, warning=FALSE, echo=FALSE, echo=FALSE, message=TRUE, warning=TRUE}

  out <- NULL
  for (omictype in names(FlomicsMultiAssay@metadata$omicList)){ 
    
    child <- paste0(omictype, ".Rmd")

    for (data in  FlomicsMultiAssay@metadata$omicList[[omictype]]){
      
      out <- c(out, knitr::knit_child(child, quiet=TRUE))  
    }
    
  }

knitr::asis_output(out)

```

`r if(length(FlomicsMultiAssay@metadata$omicList) == 0) {"\\end{comment}"}`




