# `r data` 

```{r , echo=FALSE, message=FALSE, warning=FALSE}
# Create a directory to report each dataset results
dataDir <- paste0(outDir,"/",data)
dir.create(path = dataDir, showWarnings = FALSE)
```


```{r , echo=FALSE, message=FALSE, warning=FALSE}

dataset.raw.SE <- NULL
dataset.SE     <- NULL
Diff.eval      <- FALSE
CoEx.eval      <- FALSE
Diff.ann.eval  <- FALSE
CoEx.ann.eval  <- FALSE
Diff.ann.eval_CPR <- FALSE
CoEx.ann.eval_CPR <- FALSE

dataset.raw.SE <- rflomics.MAE@ExperimentList[[paste0(data,".raw")]]
dataset.SE     <- rflomics.MAE@ExperimentList[[data]]

if(!is.null(dataset.SE)){
  
  Diff.eval      <- !is.null(dataset.SE@metadata[["DiffExpAnal"]][["Validcontrasts"]])
  CoEx.eval      <- !is.null(dataset.SE@metadata[["CoExpAnal"]]$results)
  Diff.ann.eval  <- !is.null(dataset.SE@metadata[["DiffExpEnrichAnal"]]$results)
  CoEx.ann.eval  <- !is.null(dataset.SE@metadata[["CoExpEnrichAnal"]]$results)
  
  Diff.ann.eval_CPR <- !is.null(dataset.SE@metadata[["DiffExpEnrichAnal"]])
  CoEx.ann.eval_CPR  <- !is.null(dataset.SE@metadata[["CoExpEnrichAnal"]])
}

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, eval=!is.null(dataset.SE)}

out <- NULL

out <- c(out, knitr::knit_child(paste0(path.package("RFLOMICS"), "/RFLOMICSapp/","report_03_data_explor.Rmd"),
                                quiet=TRUE))

knitr::asis_output(out)

```

<!-- differential analysis -->

```{r, echo=FALSE, message=FALSE, warning=FALSE, eval=Diff.eval}

out <- NULL

out <- c(out, knitr::knit_child(paste0(path.package("RFLOMICS"), "/RFLOMICSapp/","report_04_diff_analysis.Rmd"),
                                quiet=TRUE))

knitr::asis_output(out)

```

<!-- enrichement analysis on DE G/P/M lists with clusterprofiler -->

```{r , message=FALSE, warning=FALSE, echo=FALSE, eval=Diff.ann.eval_CPR}


out <- NULL
annot <- "DiffExpEnrichAnal"

for(ontology  in names(dataset.SE@metadata[[annot]])){
out <- c(out, knitr::knit_child(paste0(path.package("RFLOMICS"), "/RFLOMICSapp/","report_06_annot_enrich_CPR.Rmd"),
                                quiet=TRUE))
}

knitr::asis_output(out)

```

<!-- co-expression analysis -->

```{r , message=FALSE, warning=FALSE, echo=FALSE, eval=CoEx.eval}

out <- NULL


out <- c(out, knitr::knit_child(paste0(path.package("RFLOMICS"), "/RFLOMICSapp/","report_05_coexp_analysis.Rmd"),
                                quiet=TRUE))


knitr::asis_output(out)

```

<!-- enrichement analysis on cluster -->

```{r , message=FALSE, warning=FALSE, echo=FALSE, eval=CoEx.ann.eval_CPR}


out <- NULL
annot <- "CoExpEnrichAnal"

for(ontology  in names(dataset.SE@metadata[[annot]])){
out <- c(out, knitr::knit_child(paste0(path.package("RFLOMICS"), "/RFLOMICSapp/","report_06_annot_enrich_CPR.Rmd"),
                                quiet=TRUE))
}

knitr::asis_output(out)

```